# Where things are
source:       .
destination:  ./_site
plugins:      ./_plugins
layouts:      ./_layouts
paginate:     8

# Handling Reading
safe:         false
include:      [".htaccess"]
exclude:      []
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
textile_ext:  "textile"

# Filtering Content
show_drafts:  null
limit_posts:  0
future:       true
unpublished:  false

# Conversion
markdown:     kramdown
highlighter:  pygments
lsi:          false
excerpt_separator: "\n\n"

# Serving
detach:       false
port:         4000
host:         127.0.0.1
baseurl:      "" # does not include hostname

# Outputting
permalink:     date
paginate_path: /page:num
timezone:      null


#Site config
title: Mtanlee
description: Cloud技术文章
keywords: Openstack Ceph Python
url: http://mtanlee.com
feed: /atom.xml
favicon: /images/shortcut.jpg

#Nav config
nav:
  - text: 首页
    url: /index.html
  - text: 分类目录
    url: /categories.html
  - text: 文章归档
    url: /archives.html
  - text: 联系我
    url: /contact.html
  - text: 友情链接
    url: /links.html

#Author config
author:
    name: mtanlee
    email: mtanlee07@gmail.com
    imageLink: /images/header.jpg
    imageLinkgif: /images/head.gif
    simpleIntro:  Mtanlee's Blog
    simpleIntro_contacttile: 持之以恒
    detailIntro:
      <p>博客之前有写些，后来各种原因就没写了，现在重新写，这算是自己开始走入IT行业的第一步吧。</p>
      <p>关键在于持之以恒的学习，写文章，那怕是转载过来的，按照自己理解的意思再敲一遍，都比通读一遍印象更深刻。</p>
      <p>在这里与大家共勉，一起成长。</p>

#Follow me, you can choose your icon by http://fortawesome.github.io/Font-Awesome/icons/#brand
follow:
  - class: icon-rss
    url: /atom.xml
  - class: icon-weibo
    url: http://weibo.com/
  - class: icon-facebook
    url: http://facebook.com/
  - class: icon-github-alt
    url: http://github.com/
  - class: icon-twitter
    url: http://twitter.com/
  - class: icon-google-plus
    url: https://plus.google.com/112346389924534185312/about

#Links
customLinks:
  - item:
    - text: 技术小黑屋
      url: http://www.pythontab.com/
    - text: Jekyll
      url: http://jekyllrb.com
    - text: Jekyll Theme
      url: https://github.com/jekyll/jekyll/wiki/Sites
    message:  Availability
  - item:
    - text: badboy's
      url: http://wanggf62.com/
    - text: the-way-to-cloud
      url: http://iceyao.blog.51cto.com/
    - text: EinstCrazy
      url: http://einst.blog.51cto.com/
    - text: 细胞在生
      url:  http://www.cnblogs.com/wtfbk/
    - text: kula41 Tech Space
      url: http://kula41.com
    message: Friends
  - item:
    - text: Openstack
      url: http://www.openstack.org/
    - text: Ceph
      url: http://www.ceph.com/
    - text: Gitbook
      url: http://git-scm.com/doc
    - text: Python
      url: http://www.pythontab.com/
    - text: Red hat rdo
      url: https://www.rdoproject.org/Main_Page
    message: About Open source

#googleAnaly, your id link UA-12345678-X
googleAnaly:
  config: true
  id: UA-62022832-1

#baidu tongji
baiduTongji:
  config: true
  id: dc6f3e1177ad818cfa851306ccdc1f97

#comment config
disqus:
  config: false
  id:

duoshuo:
  config: true
  id: mtanlee

#baidu share config
baiduShare:
  config: true
